### ISSUE TITLE
Adding integration: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by nica-f** [dbuezas/eq3btsmart#36]
First of all let me express my gratitude for your work, this is looking really great! I have a bunch of these eQ3 thermostats and currently they stopped working with the former integration due to Python Bluetooth framework issues. So I hope to get them back now.

I did create the custom_integrations/ folder and HomeAssist picks it up obviously, I get this warning on startup:

`
2023-01-21 16:38:26.806 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dbuezas_eq3btsmart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
`

To be expected I guess.

But when I try to access the integration pressing "+ add integration" and picking it by name I get an error:

> Fehler
> Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}
> 

Sorry, it's in German, in English this would say something like "Error: Could not load configuration flow: {"message":"Invalid handler specified"}"

I have no idea whatsoever what to do with this message and/or how to diagnose and fix it - I have 30 years of C experience but little to no Python and even less HA hacking, sorry :(

FYI I just upgraded to HA release 2023.1 before doing this.

Thank you!

**Comment by nica-f** [comment]
PS: I see that you also use the python-eq3bt library to connect to the eQ3. In my setup the bleak backend does not work, which seems to have become a common problem for many. The gattlib and bluepy backends do work though. Which backend do you use by default and can this default eventually be changed if necessary?

**Comment by dbuezas** [comment]
I need to update the component to the latest home assistant version.
This component is based on that library, but has diverged quite a bit from it (so much an pull request would make no sense as it would break their CLI and pretty much everything else). This component is specifically adapted and optimized to newer HA version.
I don't know why it broke now, I use uid notify handlers instead of integers for better compatibility, it looks like that API got removed.

I will fix it soon (after I myself update HA) :)

**Comment by dbuezas** [comment]
Oh, I forgot to answer your question: no, I won't change to something other than bleak because that's the Home Assistant wants integrations to use. They put a lot of work to make all integrations work together efficiently and channel traffic through BTProxy and whatnot. 
And I also put effort into making a new async bleak endpoint with retries, etc.
Things are just in flux because home assistant is still tweaking and adding features to the Bluetooth integration, I just need to publish a fix when I have time

**Comment by nica-f** [comment]
Ah, thank you very much! Looking forward to everything and *very* much appreciate your effort :-)

Concerning bleak maybe it is just an issue with the seemingly older python-eq3bt that is fixed with your efforts? That would of course also be great. Right now I am back on the old eQ3 integration and hacked the older backend as default into it again, which makes my TRVs to show up again, but that's clearly not a healthy solution.

So I stay tuned ;)
Thanks again!

**Comment by dbuezas** [comment]
:) cool!

**Comment by dbuezas** [comment]
Ok, I just updated Home Assistant to 2023.1.7 and it is working fine. 
It looks like something went wrong with the installation of the component.
Reading the message again sehe ich, dass es nicht die Verbindung sondern das Setup von einem Gerät fehlgeschlagen hat. Also es ist nicht was ich dachte. Kannst du bitte eine Neuinstallation probieren? Die meiste Nutzer machen es durch HACS, und es ist wirklich zu empfehlen auch: es macht updates super einfach, plus es gibt viele andere frontend Komponenten und Integrations da. Das [hier](https://github.com/dbuezas/lovelace-plotly-graph-card/) zum Beispiel :)

The issue with a different backend in the old integration is that it will cause problems with other bluetooth devices.

Let me know if a reinstall or HACS fixes it!

**Comment by nica-f** [comment]
OK, so I am now running

> Home Assistant 2023.1.7
> Frontend 20230110.0 - latest

with HACS, installed your repo via HACS (removed my prior install beforehand) and I still get the same error:

> Fehler
> Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

Hmm... I have no idea what this message could mean...

This is running on a Raspberry PI4 with Raspian bullseye in a Python virtual environment.

**Comment by dbuezas** [comment]
Here somebody had the [same issue](https://community.home-assistant.io/t/error-adding-integration/485237/14?u=mateine) with another integration, and they solved it by deleting any remaining files via terminal 🤷

**Comment by dbuezas** [comment]
Assuming it's solved. Feel free to reopen if the issue persists
